// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.MatrixMultiplyTP")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp.Examples")>]
[<assembly: AssemblyDescriptionAttribute("Examples of Brahma.FSharp usage.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.MatrixMultiplyTP"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp.Examples"
    let [<Literal>] AssemblyDescription = "Examples of Brahma.FSharp usage."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
